logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube-universal]
enabled = true
app-name = "YouTube"
arch = "universal"
build-mode = "both"
version = "auto"
#patches-source = ""
#integrations-source = ""
excluded-patches = "hide-captions-button swipe-controls vanced-microg-support custom-branding-name"
included-patches = "copy-video-url custom-video-buffer disable-fullscreen-panels hide-fullscreen-panels disable-player-popup-panels hide-auto-player-popup-panels disable-shorts-on-startup disable-startup-shorts-player external-downloads hdr-auto-brightness overlay-buttons hide-get-premium hide-ads hide-general-ads hide-video-ads hide-endscreen-cards hide-endscreen-overlay hide-filmstrip-overlay hide-player-overlay hide-player-overlay-filter hide-floating-microphone-button hide-load-more-button hide-watermark hide-channel-watermark optimize-resource minimized-playback enable-minimized-playback open-links-externally premium-heading protobuf-spoof force-premium-heading remember-video-quality remove-player-controls-background return-youtube-dislike sponsorblock custom-branding-icon-mmt force-hide-player-button-background hide-player-button-background materialyou settings theme"
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "ytrv-magisk"

[YouTube-arm64-v8a]
enabled = true
app-name = "YouTube"
arch = "arm64-v8a"
build-mode = "both"
version = "auto"
#patches-source = ""
#integrations-source = ""
excluded-patches = "hide-captions-button swipe-controls vanced-microg-support custom-branding-name"
included-patches = "copy-video-url custom-video-buffer disable-fullscreen-panels hide-fullscreen-panels disable-player-popup-panels hide-auto-player-popup-panels disable-shorts-on-startup disable-startup-shorts-player external-downloads hdr-auto-brightness overlay-buttons hide-get-premium hide-ads hide-general-ads hide-video-ads hide-endscreen-cards hide-endscreen-overlay hide-filmstrip-overlay hide-player-overlay hide-player-overlay-filter hide-floating-microphone-button hide-load-more-button hide-watermark hide-channel-watermark optimize-resource minimized-playback enable-minimized-playback open-links-externally premium-heading protobuf-spoof force-premium-heading remember-video-quality remove-player-controls-background return-youtube-dislike sponsorblock custom-branding-icon-mmt force-hide-player-button-background hide-player-button-background materialyou settings theme"
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "ytrv-magisk"

[YouTube-arm-v7a]
enabled = true
app-name = "YouTube"
arch = "arm-v7a"
build-mode = "both"
version = "auto"
rv-brand = "ReVanced"
#patches-source = ""
#integrations-source = ""
excluded-patches = "hide-captions-button swipe-controls vanced-microg-support custom-branding-name"
included-patches = "copy-video-url custom-video-buffer disable-fullscreen-panels hide-fullscreen-panels disable-player-popup-panels hide-auto-player-popup-panels disable-shorts-on-startup disable-startup-shorts-player external-downloads hdr-auto-brightness overlay-buttons hide-get-premium hide-ads hide-general-ads hide-video-ads hide-endscreen-cards hide-endscreen-overlay hide-filmstrip-overlay hide-player-overlay hide-player-overlay-filter hide-floating-microphone-button hide-load-more-button hide-watermark hide-channel-watermark optimize-resource minimized-playback enable-minimized-playback open-links-externally premium-heading protobuf-spoof force-premium-heading remember-video-quality remove-player-controls-background return-youtube-dislike sponsorblock custom-branding-icon-mmt force-hide-player-button-background hide-player-button-background materialyou settings theme"
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "ytrv-magisk"

[YouTube-Extended-universal]
enabled = true
app-name = "YouTube"
arch = "universal"
build-mode = "both"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
excluded-patches = "hide-captions-button swipe-controls vanced-microg-support custom-branding-name"
included-patches = "copy-video-url custom-video-buffer disable-fullscreen-panels hide-fullscreen-panels disable-player-popup-panels hide-auto-player-popup-panels disable-shorts-on-startup disable-startup-shorts-player external-downloads hdr-auto-brightness overlay-buttons hide-get-premium hide-ads hide-general-ads hide-video-ads hide-endscreen-cards hide-endscreen-overlay hide-filmstrip-overlay hide-player-overlay hide-player-overlay-filter hide-floating-microphone-button hide-load-more-button hide-watermark hide-channel-watermark optimize-resource minimized-playback enable-minimized-playback open-links-externally premium-heading protobuf-spoof force-premium-heading remember-video-quality remove-player-controls-background return-youtube-dislike sponsorblock custom-branding-icon-mmt force-hide-player-button-background hide-player-button-background materialyou settings theme"
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "ytrv-magisk"

[YouTube-Extended-arm64-v8a]
enabled = true
app-name = "YouTube"
arch = "arm64-v8a"
build-mode = "both"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
excluded-patches = "hide-captions-button swipe-controls vanced-microg-support custom-branding-name"
included-patches = "copy-video-url custom-video-buffer disable-fullscreen-panels hide-fullscreen-panels disable-player-popup-panels hide-auto-player-popup-panels disable-shorts-on-startup disable-startup-shorts-player external-downloads hdr-auto-brightness overlay-buttons hide-get-premium hide-ads hide-general-ads hide-video-ads hide-endscreen-cards hide-endscreen-overlay hide-filmstrip-overlay hide-player-overlay hide-player-overlay-filter hide-floating-microphone-button hide-load-more-button hide-watermark hide-channel-watermark optimize-resource minimized-playback enable-minimized-playback open-links-externally premium-heading protobuf-spoof force-premium-heading remember-video-quality remove-player-controls-background return-youtube-dislike sponsorblock custom-branding-icon-mmt force-hide-player-button-background hide-player-button-background materialyou settings theme"
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "ytrv-magisk"

[YouTube-Extended-arm-v7a]
enabled = true
app-name = "YouTube"
arch = "arm-v7a"
build-mode = "both"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
excluded-patches = "hide-captions-button swipe-controls vanced-microg-support custom-branding-name"
included-patches = "copy-video-url custom-video-buffer disable-fullscreen-panels hide-fullscreen-panels disable-player-popup-panels hide-auto-player-popup-panels disable-shorts-on-startup disable-startup-shorts-player external-downloads hdr-auto-brightness overlay-buttons hide-get-premium hide-ads hide-general-ads hide-video-ads hide-endscreen-cards hide-endscreen-overlay hide-filmstrip-overlay hide-player-overlay hide-player-overlay-filter hide-floating-microphone-button hide-load-more-button hide-watermark hide-channel-watermark optimize-resource minimized-playback enable-minimized-playback open-links-externally premium-heading protobuf-spoof force-premium-heading remember-video-quality remove-player-controls-background return-youtube-dislike sponsorblock custom-branding-icon-mmt force-hide-player-button-background hide-player-button-background materialyou settings theme"
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
module-prop-name = "ytrv-magisk"

[Music-Universal]
enabled = true
app-name = "Music"
arch = "universal"
build-mode = "both"
version = "auto"
rv-brand = "ReVanced"
#patches-source = ""
#integrations-source = ""
excluded-patches = ""
included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.apps.youtube.music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
module-prop-name = "ytmrv-magisk"

[Music-arm64-v8a]
enabled = true
app-name = "Music"
arch = "arm64-v8a"
build-mode = "both"
version = "auto"
rv-brand = "ReVanced"
#patches-source = ""
#integrations-source = ""
excluded-patches = ""
included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.apps.youtube.music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
module-prop-name = "ytmrv-magisk"

[Music-arm-v7a]
enabled = true
app-name = "Music"
arch = "arm-v7a"
build-mode = "both"
version = "auto"
rv-brand = "ReVanced"
#patches-source = ""
#integrations-source = ""
excluded-patches = ""
included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.apps.youtube.music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
module-prop-name = "ytmrv-magisk"

[Music-Extended-Universal]
enabled = true
app-name = "Music"
arch = "universal"
build-mode = "both"
version = "auto"
rv-brand = "ReVanced"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
excluded-patches = ""
included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.apps.youtube.music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
module-prop-name = "ytmrv-magisk"

[Music-Extended-arm64-v8a]
enabled = true
app-name = "Music"
arch = "arm64-v8a"
build-mode = "both"
version = "auto"
rv-brand = "ReVanced"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
excluded-patches = ""
included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.apps.youtube.music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
module-prop-name = "ytmrv-magisk"

[Music-Extended-arm-v7a]
enabled = true
app-name = "Music"
arch = "arm-v7a"
build-mode = "both"
version = "auto"
rv-brand = "ReVanced"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
excluded-patches = ""
included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.google.android.apps.youtube.music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
module-prop-name = "ytmrv-magisk"

[Messenger-arm64-v8a]
enabled = true
app-name = "Messenger"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.facebook.orca/"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
arch = "arm64-v8a"

[Messenger-arm-v7a]
enabled = true
app-name = "Messenger"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
apkmonk-dlurl = "https://www.apkmonk.com/app/com.facebook.orca/"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
arch = "arm-v7a"

[Twitter]
enabled = false
build-mode = "apk"
excluded-patches = "hide-views-stats"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitter-inc/twitter/"

[Twitch]
enabled = false
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"

[TikTok]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Reddit]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"



[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Citra]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"
arch = "arm64-v8a"

[Backdrops]
enabled = false
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[WarnWetter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Windyapp]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[TickTick]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/appest-inc/ticktick-to-do-list-with-reminder-day-planner/"
arch = "arm64-v8a"

[Tasker]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/joaomgcd/tasker/"

[Photomath]
enabled = false
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"
